---
- name: start postgresql
  service: name=postgresql state=started enabled=yes

- name: restart postgresql
  service: name=postgresql state=restarted

- name: stop postgresql
  service: name=postgresql state=stoped

- name: start repmgrd
  service: name=repmgrd state=started enabled=yes

- name: restart repmgrd
  service: name=repmgrd state=restarted

- name: stop repmgrd
  service: name=repmgrd state=stoped
